spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Dkq@1995
    url: jdbc:mysql://81.70.16.9:3306/demo?serverTimezone=UTC&characterEncoding=UTF-8
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath:mappers/*.xml